name: CI-CD

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pytest -q

  build_and_push_image:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta (image tags)
        id: meta
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${REPO_LOWER}:$GITHUB_SHA" >> $GITHUB_OUTPUT
          echo "LATEST=ghcr.io/${REPO_LOWER}:latest" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          docker build -t ${{ steps.meta.outputs.IMAGE }} -t ${{ steps.meta.outputs.LATEST }} .

      - name: Push
        run: |
          docker push ${{ steps.meta.outputs.IMAGE }}
          docker push ${{ steps.meta.outputs.LATEST }}

  deploy:
    needs: build_and_push_image
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy hook
        run: curl -fsSL -X POST "${{ secrets.RENDER_HOOK_URL }}"
